#!groovy

// Generated by IBM TransformationAdvisor
// Fri Apr 19 16:42:34 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}